repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v1.4.0
    hooks:
      - id: gofmt
      - id: govet
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.59.0
    hooks:
      - id: golangci-lint
        args: [./...]
